apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  # Default admin password (change in production): admin123
  # bcrypt hash of "admin123"
  admin.password: JDJhJDEwJEZxRVlBQnpHaGN6aHMxdlF0RGFCYnVrYVhZSzdGRy9mZzdZVmlhcjEzY1l1YlZpT2hvdGt1
  # Server signature key (base64 encoded random 32 bytes)
  server.secretkey: YUhSMGNITTZMeTl5WVc1a2IyMXVaWE56TG05eVp5OW5aVzVsY21GMFpTOHlORGNq
  # TLS private key and certificate (optional - for HTTPS)
  # tls.crt: LS0tLS1CRUdJTi...
  # tls.key: LS0tLS1CRUdJTi...
stringData:
  # Repository server connection details
  dex.github.clientId: ""
  dex.github.clientSecret: ""
  # OIDC configuration
  oidc.config: |
    name: OIDC
    issuer: https://keycloak.dev.smartcity.local/auth/realms/master
    clientId: argocd
    clientSecret: argocd-secret
    requestedScopes: ["openid", "profile", "email", "groups"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
