apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
  namespace: smartcity
  labels:
    app: mongodb
    component: backup
    environment: development
  annotations:
    description: "Persistent storage for MongoDB backups in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
