apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: smartcity
spec:
  template:
    spec:
      containers:
      - name: keycloak
        envFrom:
        - configMapRef:
            name: keycloak-config
