apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: smartcity
  labels:
    app: keycloak
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: secret
    app.kubernetes.io/part-of: smartcity
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin123
