apiVersion: v1
kind: Service
metadata:
  name: house-control
  namespace: house-control
  labels:
    app: house-control-container
    component: application
    environment: development
spec:
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: house-control-container
  type: ClusterIP
