apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgres-staging

# Base configuration
bases:
  - ../../

# Environment-specific labels
commonLabels:
  environment: staging

# Namespace for staging
namespace: smartcity-staging

# Image for staging
images:
  - name: postgres
    newTag: "15-alpine"

# Patches for staging environment
patchesStrategicMerge:
  - postgres-staging-patch.yaml

# Resource adjustments for staging
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: postgres
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: postgres-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 20Gi
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: postgres-backup-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 50Gi
