name: Deploy PostgreSQL
on:
  push:
    paths:
      - 'k8s/infra/dev/postgres/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy PostgreSQL
        run: |
          cd k8s/infra/dev/postgres
          ./deploy-postgres.sh

      - name: Health Check
        run: |
          cd k8s/infra/dev/postgres
          ./health-check-postgres.sh

      - name: Test External Connection
        run: |
          cd k8s/infra/dev/postgres
          ./test-external-connection.sh
