version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smartcity
      POSTGRES_USER: smartcity
      POSTGRES_PASSWORD: smartcity123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smartcity -d smartcity"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - smartcity

volumes:
  postgres_data:

networks:
  smartcity:
    driver: bridge
