apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgres
  namespace: smartcity

resources:
  - postgres-configmap.yaml
  - postgres-init-configmap.yaml
  - postgres-secret.yaml
  - postgres-pvc.yaml
  - postgres-statefulset.yaml
  - postgres-service-external.yaml
  - postgres-tls-certificate.yaml
  - postgres-networkpolicy.yaml
  - postgres-backup-configmap.yaml
  - postgres-backup-cronjob.yaml
  - postgres-backup-pvc.yaml

commonLabels:
  app: postgres
  component: database
  environment: development
  project: smartcity
  managed-by: kustomize

configMapGenerator:
  - name: postgres-config
    behavior: replace
    files:
      - postgresql.conf=postgres-advanced-config.conf

images:
  - name: postgres
    newTag: "15-alpine"

replicas:
  - name: postgres
    count: 1
