apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: postgres
  namespace: smartcity

# Common labels applied to all resources
commonLabels:
  app: postgres
  component: database
  environment: development

# Resources to include
resources:
  - postgres-secret.yaml
  - postgres-configmap.yaml
  - postgres-init-configmap.yaml
  - postgres-pvc.yaml
  - postgres-backup-pvc.yaml
  - postgres-backup-configmap.yaml
  - postgres-statefulset.yaml
  - postgres-networkpolicy.yaml
  - postgres-backup-cronjob.yaml

# ConfigMap generator for additional configurations (if needed)
# configMapGenerator:
#   - name: postgres-extra-config
#     literals:
#       - POSTGRESQL_MAX_CONNECTIONS=100
#       - POSTGRESQL_SHARED_BUFFERS=128MB

# Secret generator (disabled for production - use explicit secrets)
# secretGenerator:
#   - name: postgres-secret
#     literals:
#       - postgres-username=smartcity
#       - postgres-password=smartcity123
#     type: Opaque

# Image transformations (for different environments)
images:
  - name: postgres
    newTag: "15-alpine"

# Namespace transformation
namespace: smartcity

# Resource patches for different environments
patchesStrategicMerge: []

# JSON patches for fine-tuning
patches: []

# Replica count patches for different environments
# patchesJson6902:
#   - target:
#       group: apps
#       version: v1
#       kind: StatefulSet
#       name: postgres
#     patch: |-
#       - op: replace
#         path: /spec/replicas
#         value: 1

# ConfigMap patches for different environments
# - target:
#     version: v1
#     kind: ConfigMap
#     name: postgres-config
#   patch: |-
#     - op: replace
#       path: /data/postgresql.conf
#       value: |
#         # Production configuration
#         max_connections = 200
#         shared_buffers = 256MB
#         effective_cache_size = 1GB
#         work_mem = 8MB
#         maintenance_work_mem = 128MB

# Resource limits patches for different environments
# - target:
#     group: apps
#     version: v1
#     kind: StatefulSet
#     name: postgres
#   patch: |-
#     - op: replace
#       path: /spec/template/spec/containers/0/resources
#       value:
#         requests:
#           cpu: "500m"
#           memory: "1Gi"
#         limits:
#           cpu: "1000m"
#           memory: "2Gi"
