apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-pvc
  namespace: smartcity
  labels:
    app: postgres
    component: backup
    environment: development
  annotations:
    description: "Persistent storage for PostgreSQL backups in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
