apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: smartcity
  labels:
    app: postgres
    component: database
    environment: development
data:
  postgresql.conf: |
    # PostgreSQL configuration for Smart City application

    # Connection Settings
    listen_addresses = '*'
    port = 5432
    max_connections = 100
    shared_preload_libraries = 'pg_stat_statements'

    # Memory Settings
    shared_buffers = 128MB
    effective_cache_size = 256MB
    work_mem = 4MB
    maintenance_work_mem = 64MB

    # Checkpoint Settings
    checkpoint_segments = 32
    checkpoint_completion_target = 0.9
    wal_buffers = 16MB
    wal_writer_delay = 200ms

    # Logging Settings
    log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    log_statement = 'ddl'
    log_duration = on
    log_min_duration_statement = 1000
    log_checkpoints = on
    log_connections = on
    log_disconnections = on
    log_lock_waits = on
    log_temp_files = 0

    # Performance Settings
    random_page_cost = 1.1
    effective_io_concurrency = 200
    autovacuum = on
    autovacuum_max_workers = 3
    autovacuum_naptime = 20s
    autovacuum_vacuum_threshold = 50
    autovacuum_analyze_threshold = 50

    # Security Settings
    ssl = off
    password_encryption = scram-sha-256

    # Extension Settings
    pg_stat_statements.max = 10000
    pg_stat_statements.track = all
    pg_stat_statements.track_utility = off
