apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-tls
  namespace: smartcity
  labels:
    app: postgres
    component: database
    environment: development
spec:
  secretName: postgres-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - postgres.dev.smartcity.local
