apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: smartcity
  labels:
    app: redis
    component: cache
    environment: development
data:
  redis.conf: |
    # Redis configuration for Smart City application

    # Network
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300

    # Security
    requirepass smartcity123
    protected-mode yes

    # Memory Management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 5

    # Persistence
    save 900 1
    save 300 10
    save 60 10000

    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec

    # Logging
    loglevel notice
    logfile ""

    # Performance
    tcp-backlog 511
    databases 16

    # Connection
    maxclients 10000

    # Replication (prepared for future scaling)
    # replicaof <masterip> <masterport>
    # masterauth <master-password>

    # Sentinel (prepared for future HA)
    # sentinel monitor mymaster 127.0.0.1 6379 2
    # sentinel auth-pass mymaster smartcity123

    # Cluster (prepared for future clustering)
    # cluster-enabled yes
    # cluster-config-file nodes.conf
    # cluster-node-timeout 5000

    # Advanced Configuration
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    stream-node-max-bytes 4096
    stream-node-max-entries 100

    # Disable dangerous commands
    rename-command FLUSHDB ""
    rename-command FLUSHALL ""
    rename-command SHUTDOWN SHUTDOWN_REDIS
    rename-command CONFIG CONFIG_REDIS
    rename-command DEBUG DEBUG_REDIS

    # Enable AOF rewrite
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb

    # Slow log
    slowlog-log-slower-than 10000
    slowlog-max-len 128

    # Latency monitoring
    latency-monitor-threshold 100
