apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
  namespace: smartcity
  labels:
    app: redis
    component: backup
    environment: development
spec:
  schedule: "0 4 * * *"  # Daily at 4:00 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: redis
            component: backup
            environment: development
        spec:
          restartPolicy: OnFailure
          containers:
            - name: redis-backup
              image: redis:7.2-alpine
              command:
                - /bin/sh
                - -c
                - /scripts/backup.sh
              env:
                - name: REDIS_HOST
                  value: "redis.smartcity.svc.cluster.local"
                - name: REDIS_PORT
                  value: "6379"
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis-secret
                      key: redis-password
              volumeMounts:
                - name: backup-scripts
                  mountPath: /scripts
                  readOnly: true
                - name: backup-storage
                  mountPath: /backup
              resources:
                requests:
                  cpu: "100m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"
          volumes:
            - name: backup-scripts
              configMap:
                name: redis-backup-config
                defaultMode: 0755
            - name: backup-storage
              persistentVolumeClaim:
                claimName: redis-backup-pvc
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
