apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-backup-pvc
  namespace: smartcity
  labels:
    app: redis
    component: backup
    environment: development
  annotations:
    description: "Persistent storage for Redis backups in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
