# rabbitmq-values-minikube.yaml
# Configuração otimizada para rodar o RabbitMQ da Bitnami em Minikube.

# --- Autenticação ---
# Define o usuário e senha para acessar o RabbitMQ (tanto para apps quanto para a UI de gerenciamento).
auth:
  username: "user"
  password: "rabbitmq123" # IMPORTANTE: Troque esta senha

# --- Persistência ---
# Desabilitamos a persistência para economizar recursos e evitar a complexidade de
# PersistentVolumeClaims em um ambiente de estudo.
# ATENÇÃO: Todas as filas e mensagens serão perdidas se o Pod reiniciar.
persistence:
  enabled: false

# --- Otimização de Recursos (CPU/Memória) ---
# Alocamos recursos mínimos para o nó do RabbitMQ.
# A Erlang VM (na qual o RabbitMQ roda) pode ser sensível à memória,
# mas para estudo estes valores são um bom ponto de partida.
resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "300m"
    memory: "512Mi"

# --- Management Plugin ---
# A interface de gerenciamento é extremamente útil para aprendizado e vem habilitada por padrão.
# Apenas garantimos que o serviço seja criado para ela.
management:
  enabled: true

# --- Desabilitar Métricas ---
# Para manter a instalação o mais leve possível, desabilitamos o Prometheus exporter.
metrics:
  enabled: true