apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-control
  namespace: smart
  labels:
    app: house-control-container
    component: application
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-control-container
  template:
    metadata:
      labels:
        app: house-control-container
        component: application
        environment: development
    spec:
      containers:
      - name: house-control-container
        image: ghcr.io/alessandrorsseixas/smart-city-org/house-control:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        envFrom:
        - configMapRef:
            name: house-control-config
        - secretRef:
            name: house-control-secret
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: house-control-config
