apiVersion: v1
kind: ConfigMap
metadata:
  name: house-control-config
  namespace: smartcity
  labels:
    app: house-control-container
    component: application
    environment: development
data:
  application.yml: |
    # Spring Boot configuration for House Control application

    spring:
      datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/house_control}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:postgres}
      redis:
        host: ${SPRING_REDIS_HOST:redis}
        port: ${SPRING_REDIS_PORT:6379}
      rabbitmq:
        host: ${SPRING_RABBITMQ_HOST:rabbitmq}
        port: ${SPRING_RABBITMQ_PORT:5672}
        username: ${RABBITMQ_USERNAME:guest}
        password: ${RABBITMQ_PASSWORD:guest}

    keycloak:
      auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080/auth}
      realm: ${KEYCLOAK_REALM:smartcity}
      resource: ${KEYCLOAK_RESOURCE:house-control}
      client-secret: ${KEYCLOAK_CLIENT_SECRET:house-control-secret}

    app:
      messaging:
        queues:
          house-commands: ${HOUSE_COMMAND_QUEUE:house.commands.q}

    logging:
      level:
        root: INFO
        org.springframework: INFO
        org.springframework.security: DEBUG
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics
      endpoint:
        health:
          show-details: when-authorized

    server:
      port: 8080
      servlet:
        context-path: /