kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: house-control-hpa
  namespace: house-control
  labels:
    app: house-control-container
    component: application
    environment: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: house-control
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80  # Target average CPU utilization percentage