apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rabbitmq
  namespace: smartcity

commonLabels:
  app: rabbitmq
  component: messaging
  environment: development
  managed-by: kustomize

resources:
  - rabbitmq-secret.yaml
  - rabbitmq-configmap.yaml
  - rabbitmq-pvc.yaml
  - rabbitmq-backup-pvc.yaml
  - rabbitmq-backup-configmap.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-networkpolicy.yaml
  - rabbitmq-backup-cronjob.yaml

images:
  - name: rabbitmq
    newTag: "3.11-management-alpine"
  - name: curlimages/curl
    newTag: "latest"
