apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: smartcity
  labels:
    app: rabbitmq
    component: messaging
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        component: messaging
        environment: development
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: rabbitmq
          image: rabbitmq:3.11-management-alpine
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  # RabbitMQ needs write access
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-username
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
            - name: RABBITMQ_ERLANG_COOKIE
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-erlang-cookie
            - name: RABBITMQ_NODENAME
              value: "rabbit@rabbitmq.smartcity.svc.cluster.local"
            - name: RABBITMQ_USE_LONGNAME
              value: "true"
            - name: RABBITMQ_LOGS
              value: "-"
            - name: RABBITMQ_SASL_LOGS
              value: "-"
          ports:
            - containerPort: 5672
              name: amqp
              protocol: TCP
            - containerPort: 15672
              name: management
              protocol: TCP
            - containerPort: 15692
              name: prometheus
              protocol: TCP
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
            - name: rabbitmq-enabled-plugins
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - status
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 30
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - "rabbitmqctl stop_app"
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
        - name: rabbitmq-enabled-plugins
          configMap:
            name: rabbitmq-config
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: smartcity
  labels:
    app: rabbitmq
    component: messaging
    environment: development
spec:
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
    - port: 15692
      targetPort: 15692
      protocol: TCP
      name: prometheus
  selector:
    app: rabbitmq
  type: ClusterIP
