apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-backup-pvc
  namespace: smartcity
  labels:
    app: rabbitmq
    component: backup
    environment: development
  annotations:
    description: "Persistent storage for RabbitMQ backups in Smart City application"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
